drop table if exists patient CASCADE;
drop table if exists vaccination_point CASCADE;
drop table if exists vaccination_point_vaccine_stock CASCADE;
drop table if exists vaccine CASCADE;
drop table if exists vaccine_data CASCADE;

create table patient (
                         id bigint generated by default as identity,
                         age integer not null,
                         full_name varchar(255),
                         gender varchar(255),
                         is_vaccinated boolean not null,
                         vaccination_date varchar(255),
                         vaccine_name varchar(255),
                         primary key (id)
);

create table vaccination_point (
                                   id bigint generated by default as identity,
                                   address varchar(255),
                                   city varchar(255),
                                   name varchar(255),
                                   region varchar(255),
                                   primary key (id)
);

create table vaccination_point_vaccine_stock (
                                                 vaccination_point_id bigint not null,
                                                 vaccine_stock_id bigint not null
);

create table vaccine (
                         id bigint generated by default as identity,
                         vaccination_point_id bigint,
                         vaccine_data_name varchar(255),
                         primary key (id)
);

create table vaccine_data (
                              name varchar(255) not null,
                              doses_needed integer not null,
                              min_age integer not null,
                              primary key (name)
);

alter table vaccination_point_vaccine_stock
    add constraint UK_k34snc5mx75gvdhqmqtlhpfsx unique (vaccine_stock_id);

alter table patient
    add constraint FK548x7r3tvvgfc5ksdgik7iean
        foreign key (vaccine_name)
            references vaccine_data;

alter table vaccination_point_vaccine_stock
    add constraint FKc8jl5mg13nyavaw3rvtn57om5
        foreign key (vaccine_stock_id)
            references vaccine;

alter table vaccination_point_vaccine_stock
    add constraint FK6udyt071vxxtme3fykdr3of1r
        foreign key (vaccination_point_id)
            references vaccination_point;

alter table vaccine
    add constraint FKq3ndlxqk6ud4j9s5j09n6ht0k
        foreign key (vaccination_point_id)
            references vaccination_point;

alter table vaccine
    add constraint FKgxmh6vybhfc1yoinaa9orei0p
        foreign key (vaccine_data_name)
            references vaccine_data